---
title: CV
name: Marie
surname: Bouffard
Location: "Santa Barbara, California"
phone: 802-735-8472
email: "mariebouffard@ucsb.edu"
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::markdowncv:
    theme: kjhealy
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

## Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Master of Environmental Science and Management", "2021", "University of California, Santa Barbara (UCSB)", "Bren School of Environmental Science & Management",
  "Bachelor of Arts in Communication", "2017", "Villanova University", "Greater Philadelphia, Pennsylvania",
  "Sustainability in Northern Europe Study Abroad Program", "2016", "DIS", "Copenhagen, Denmark"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

## Experience

```{r consulting}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  "Geospatial Data Analyst and Communication Specialist", "University of Vermont Spatial Analysis Lab", "Burlington, Vermont", "10/21 – Present", "Conducted geospatial analysis for urban tree cover assesments and led data visualization creation for reports aimed at decison makers and local stakeholders.",
  "Conservation Intern", "Osa Conservation", "Costa Rica", "6/20 - 9/20", "Developed spatial analysis to support Osa Conservation’s work and provide farmers with the necessary information to implement sustainable farming practices in a manner that is beneficial to them and the local wildlife.",
  "Graduate Teaching Assistant", "UCSB", "Santa Barbara, CA", "9/19 – 3/20", "Developed lesson plans, managed grading, and taught LING50: Language and Power (Linguistics Department) and COMM 1: Introduction to Communication (Department of Communication).",
  "Center Lead", "NASA DEVELOP", "Athens, Georgia", "9/18 – 5/19", "Led NASA DEVELOP’s Georgia Node by managing all node projects, research teams, hiring, and communications with partners and stakeholders. Developed 5 research proposals that were funded by NASA Applied Sciences Division. Served on the NASA DEVELOP strategic communication initiative team by holding science communication workshops, and writing content for program social media. Attended NASA DEVELOP Leadership Conference 2019 at NASA Langley Research Center to provide input on future and direction of the program.",
    "Outdoor Education Instructor", "Keystone Science School", "Keystone, Colorado", "9/17 – 5/18", "Created place-based environmental science curriculum for summer programs. Led groups of 13 students aged 7 to 17 on back country camping and backpacking trips throughout Colorado.",
  "Research Consultant", "NASA DEVELOP", "Athens, Georgia", "9/17 – 5/18", "Conducted geospatial analysis to provide data for government and international NGO project partners for their decision making on environmental policy issues. Led deliverable creation and technical reports for project team.",
  "Residential Outdoor Educator", "Smithsonian Conservation Biological Institute", "Front Royal, Virginia", "6/16-8/16 and 6/17 and 8/17", "Developed and taught 90-minute weekly lessons on ecology, environmental conservation, plant identification, science writing, maps, and sustainable food systems for students aged 11 to 16. Served as an ambassador for the Friends of the National Zoo (FONZ).",
) %>% 
  detailed_entries(role, dates, company, loc, details)
```