---
title: CV
name: Marie
surname: Curie
position: "Professor"
address: "School of Physics & Chemistry, École Normale Supérieure"
phone: +1 22 3333 4444
www: mariecurie.com
email: "Marie.Curie@ens.fr"
twitter: mariecurie
github: mariecurie
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Marie is a Polish and naturalized-French physicist and chemist who conducts pioneering research on radioactivity."
output: 
  vitae::markdowncv:
    theme: kjhealy
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

## Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

## Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Master of Environmental Science and Management", "2021", "University of California, Santa Barbara (UCSB)", "Bren School of Environmental Science & Management",
  "Bachelor of Arts in Communication", "2017", "Villanova University", "Greater Philadelphia, Pennsylvania",
  "Sustainability in Northern Europe Study Abroad Program", "2016", "DIS", "Copenhagen, Denmark"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

## Nobel Prizes

```{r consulting}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  "Data scientist", "Nectric", "Clayton, Australia", "Jan. 2019 - Present", "A variety of consulting projects with substantial spatio-temporal modelling tasks.",
  "Research assistant", "Monash University", "Clayton, Australia", "Jan. 2016 - Present", "Involved in many internal and external data projects of varying size and complexity.",
  "Research assistant", "Monash University", "Clayton, Australia", "Jan. 2016 - Present", "Projects typically feature large scale time series modelling or analysis, cross-sectional modelling and creating tools for improving workflows.",
  "Research assistant", "Monash University", "Clayton, Australia", "Jan. 2016 - Present", "Consulting project clients include: Huawei, Monash University, R Consortium, NSW Chief Scientist office, DiabetesLab and Tennis Australia.",
  "Data mining intern", "iSelect", "Cheltenham, Australia", "Feb. 2015 - Mar. 2015", "Improved business reporting with interactive visualisations, and model-based anomaly detection.",
) %>% 
  detailed_entries(role, dates, company, loc, details)
```

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

## Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

